name: issue-greeter
on:
  issues:
    types: [opened]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        env:
          REPO: ${{ github.event.repository.name }}
          OWNER: ${{ github.event.repository.owner.login }}
          NUMBER: ${{ github.event.issue.number }}
        run: |
          curl -s -X POST https://api.github.com/repos/$OWNER/$REPO/issues/$NUMBER/comments \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"body":"Hello ${{ github.event.issue.user.login }}, thanks for your issue!"}'
