name: repository-dispatch-2
on:
  repository_dispatch:
    types: [my-type]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          echo "${{ github.event.client_payload.foo }}"
          echo "${{ github.event.client_payload.bar }}"
