name: conditionals-4
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - if: success()
        name: step-1
        run: echo "Step 1"
      - if: success()
        name: step-2
        run: echo "Step 2"
