name: conditionals-2
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: echo "Step 1"
      - name: step-2
        run: exit 1
      - if: success()
        name: step-3
        run: echo "Step 3"
      - if: failure()
        name: step-4
        run: echo "Step 4"
      - if: always()
        name: step-5
        run: echo "Step 5"
