name: conditionals-2
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: echo "Step 1"
      - name: step-2
        run: exit 1
      - name: step-3
        if: success()
        run: echo "Step 3"
      - name: step-4
        if: failure()
        run: echo "Step 4"
      - name: step-5
        if: always()
        run: echo "Step 5"
