name: conditionals-6
on:
  issues:
    types: [opened]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: handle-all-issues
        run: echo "This step runs for all issues" && exit 1
      - if: always() && startsWith(github.event.issue.title, 'bug')
        name: handle-bug-reports
        run: echo "This step runs only for bug reports"
      - if: failure() && startsWith(github.event.issue.title, 'feature request')
        name: handle-feature-requests
        run: echo "This step runs only for feature requests"
