name: conditionals-5
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - if: true
        name: step-1
        run: echo "Step 1"
      - if: 1 == 1
        name: step-2
        run: echo "Step 2"
      - if: startsWith("foo", 'f')
        name: step-3
        run: echo "Step 3"
