name: outputs-1
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        id: xyz
        run: echo "::set-output name=ip-address::$(curl -s ifconfig.me)"
