name: outputs
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        id: step-1
        run: echo "::set-output name=ip-address::$(curl -s ifconfig.me)"
      - name: step-2
        run: echo "${{ steps.step-1.outputs.ip-address }}"
